-- ============================================================================
--  AgroSmart - Modelo Relacional (Oracle)
--  Script de criação de tabelas, chaves primárias e estrangeiras.
--
--  Compatível com Oracle 12c+ (usa colunas IDENTITY).
--  Execute no Oracle SQL Developer conectado ao seu schema.
--
--  Observação: este script é a versão "limpa/legível" do schema. O mesmo
--  schema também pode ser aplicado via EF Core (99_ef_idempotent_oracle.sql)
--  ou via `dotnet ef database update`.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) REGIÕES (módulos / baias de cultivo da estufa orbital)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_REGIONS (
    Id              NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Code            NVARCHAR2(30)  NOT NULL,
    Name            NVARCHAR2(120) NOT NULL,
    ModuleType      NVARCHAR2(60),
    FieldLocation  NVARCHAR2(120),
    Description     NVARCHAR2(500),
    CreatedAt       TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REGION PRIMARY KEY (Id),
    CONSTRAINT UX_REGION_CODE UNIQUE (Code)
);

-- ---------------------------------------------------------------------------
-- 2) CATÁLOGO DE MÉTRICAS AMBIENTAIS
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_METRIC_TYPES (
    Id          NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Code        NVARCHAR2(30)  NOT NULL,
    Name        NVARCHAR2(80)  NOT NULL,
    Unit        NVARCHAR2(20)  NOT NULL,
    Description NVARCHAR2(300),
    NominalMin  BINARY_DOUBLE,
    NominalMax  BINARY_DOUBLE,
    CONSTRAINT PK_METRIC_TYPE PRIMARY KEY (Id),
    CONSTRAINT UX_METRIC_CODE UNIQUE (Code)
);

-- ---------------------------------------------------------------------------
-- 3) USUÁRIOS (operadores autenticados via JWT)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_USERS (
    Id           NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Email        NVARCHAR2(150) NOT NULL,
    PasswordHash NVARCHAR2(300) NOT NULL,
    Role         NVARCHAR2(30)  NOT NULL,
    CreatedAt    TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (Id),
    CONSTRAINT UX_USER_EMAIL UNIQUE (Email)
);

-- ---------------------------------------------------------------------------
-- 4) DISPOSITIVOS / SENSORES DE CAMPO (vinculados a uma região)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_DEVICES (
    Id              NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Identifier      NVARCHAR2(50)  NOT NULL,
    Name            NVARCHAR2(120) NOT NULL,
    DeviceType      NVARCHAR2(60),
    Status          NVARCHAR2(20)  NOT NULL,
    FirmwareVersion NVARCHAR2(30),
    InstalledAt     TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    LastSeenAt      TIMESTAMP(7),
    RegionId        NUMBER(10)     NOT NULL,
    CONSTRAINT PK_DEVICE PRIMARY KEY (Id),
    CONSTRAINT UX_DEVICE_IDENT UNIQUE (Identifier),
    CONSTRAINT FK_DEVICE_REGION FOREIGN KEY (RegionId)
        REFERENCES AGS_REGIONS (Id)
);

-- ---------------------------------------------------------------------------
-- 5) REGRAS DE ALERTA (limiares configuráveis por métrica / região)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_ALERT_RULES (
    Id           NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Name         NVARCHAR2(120) NOT NULL,
    Description  NVARCHAR2(300),
    MetricTypeId NUMBER(10)     NOT NULL,
    RegionId     NUMBER(10),                       -- NULL = aplica-se a todas as regiões
    MinThreshold BINARY_DOUBLE,
    MaxThreshold BINARY_DOUBLE,
    Severity     NVARCHAR2(20)  NOT NULL,
    IsActive     NUMBER(1)      DEFAULT 1 NOT NULL, -- 0 = inativa, 1 = ativa
    CreatedAt    TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERT_RULE PRIMARY KEY (Id),
    CONSTRAINT FK_RULE_METRIC FOREIGN KEY (MetricTypeId)
        REFERENCES AGS_METRIC_TYPES (Id),
    CONSTRAINT FK_RULE_REGION FOREIGN KEY (RegionId)
        REFERENCES AGS_REGIONS (Id)
);

-- ---------------------------------------------------------------------------
-- 6) LEITURAS DE SENSOR (1 evento de coleta = 1 arquivo JSON)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_SENSOR_READINGS (
    Id          NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CollectedAt TIMESTAMP(7)   NOT NULL,
    ReceivedAt  TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    SourceFile  NVARCHAR2(150),
    DeviceId    NUMBER(10)     NOT NULL,
    CONSTRAINT PK_READING PRIMARY KEY (Id),
    CONSTRAINT FK_READING_DEVICE FOREIGN KEY (DeviceId)
        REFERENCES AGS_DEVICES (Id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- 7) MEDIÇÕES (cada valor de métrica dentro de uma leitura)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_MEASUREMENTS (
    Id              NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Value           BINARY_DOUBLE NOT NULL,
    SensorReadingId NUMBER(10)    NOT NULL,
    MetricTypeId    NUMBER(10)    NOT NULL,
    CONSTRAINT PK_MEASUREMENT PRIMARY KEY (Id),
    CONSTRAINT FK_MEAS_READING FOREIGN KEY (SensorReadingId)
        REFERENCES AGS_SENSOR_READINGS (Id) ON DELETE CASCADE,
    CONSTRAINT FK_MEAS_METRIC FOREIGN KEY (MetricTypeId)
        REFERENCES AGS_METRIC_TYPES (Id)
);

-- ---------------------------------------------------------------------------
-- 8) ALERTAS (gerados pela ingestão ou criados manualmente)
-- ---------------------------------------------------------------------------
CREATE TABLE AGS_ALERTS (
    Id                   NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Message              NVARCHAR2(400) NOT NULL,
    Severity             NVARCHAR2(20)  NOT NULL,
    Status               NVARCHAR2(20)  NOT NULL,
    TriggeredValue       BINARY_DOUBLE  NOT NULL,
    CreatedAt            TIMESTAMP(7)   DEFAULT SYSTIMESTAMP NOT NULL,
    AcknowledgedAt       TIMESTAMP(7),
    ResolvedAt           TIMESTAMP(7),
    AlertRuleId          NUMBER(10),
    MetricTypeId         NUMBER(10)     NOT NULL,
    MeasurementId        NUMBER(10),
    DeviceId             NUMBER(10)     NOT NULL,
    RegionId             NUMBER(10)     NOT NULL,
    AcknowledgedByUserId NUMBER(10),
    CONSTRAINT PK_ALERT PRIMARY KEY (Id),
    CONSTRAINT FK_ALERT_RULE   FOREIGN KEY (AlertRuleId)          REFERENCES AGS_ALERT_RULES (Id),
    CONSTRAINT FK_ALERT_METRIC FOREIGN KEY (MetricTypeId)         REFERENCES AGS_METRIC_TYPES (Id),
    CONSTRAINT FK_ALERT_MEAS   FOREIGN KEY (MeasurementId)        REFERENCES AGS_MEASUREMENTS (Id) ON DELETE SET NULL,
    CONSTRAINT FK_ALERT_DEVICE FOREIGN KEY (DeviceId)             REFERENCES AGS_DEVICES (Id),
    CONSTRAINT FK_ALERT_REGION FOREIGN KEY (RegionId)             REFERENCES AGS_REGIONS (Id),
    CONSTRAINT FK_ALERT_USER   FOREIGN KEY (AcknowledgedByUserId) REFERENCES AGS_USERS (Id) ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- Índices de apoio (consultas por chave estrangeira / status)
-- ---------------------------------------------------------------------------
CREATE INDEX IX_DEVICE_REGION   ON AGS_DEVICES        (RegionId);
CREATE INDEX IX_RULE_METRIC     ON AGS_ALERT_RULES    (MetricTypeId);
CREATE INDEX IX_RULE_REGION     ON AGS_ALERT_RULES    (RegionId);
CREATE INDEX IX_READING_DEVICE  ON AGS_SENSOR_READINGS(DeviceId);
CREATE INDEX IX_MEAS_READING    ON AGS_MEASUREMENTS   (SensorReadingId);
CREATE INDEX IX_MEAS_METRIC     ON AGS_MEASUREMENTS   (MetricTypeId);
CREATE INDEX IX_ALERT_STATUS    ON AGS_ALERTS         (Status);
CREATE INDEX IX_ALERT_REGION    ON AGS_ALERTS         (RegionId);
CREATE INDEX IX_ALERT_DEVICE    ON AGS_ALERTS         (DeviceId);
CREATE INDEX IX_ALERT_METRIC    ON AGS_ALERTS         (MetricTypeId);

COMMIT;
